networks:
      mern-stack:
        external: true
services:
 frontend:
    image: faizansari2025/blog-client
    container_name: react
    restart: always
    networks:
      - mern-stack
       
    ports:
      - 4173:4173
 
    depends_on:
      - server
 server:
    image: faizansari2025/blog-server
    container_name: nodejs
    restart: always
    networks:
      - mern-stack
   
    ports:
      - 3000:3000
    environment:
      - DB_URL=mongodb+srv://faizansari2025:Bandarfaiz@cluster0.v4fha.mongodb.net/bloglivedeploy
      - TOKEN="12256447336376@#@@$$55454544@@$#6%^599((*(&^%)))"
      -  PORT=3000
    depends_on:
      - db
 db:
    image: mongodb/atlas
    container_name: mongodb
    restart: always
    networks:
      - mern-stack
        
    ports:
      - 27017:27017
    # environment:
    #   - MONGODB_INITDB_ROOT_USERNAME=user
    #   - MONGODB_INITDB_ROOT_PASSWORD=pass
   
    volumes:
      - data:/data/db
      - config:/data/configdb


volumes:
  data:
  config: