services:
 frontend:
    image: faizansari2025/blog-client
    container_name: react
    ports:
      - 4173:4173
 
    depends_on:
      - server
 server:
    image: faizansari2025/blog-server
    container_name: nodejs
    ports:
      - 3000:3000
    environment:
      - DB_URL=mongodb://db/bloglive
      - TOKEN="12256447336376@#@@$$55454544@@$#6%^599((*(&^%)))"
      -  PORT=3000
    depends_on:
      - db
 db:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    # environment:
    #  MONGO_INITDB_ROOT_USERNAME: admin
    #  MONGO_INITDB_ROOT_PASSWORD: admin
   
    volumes:
      - mongo_db:/data/db


volumes:
      mongo_db: 
        external: true