name : blog workfllow


on:
 push:
   branches:
    - main

jobs:
  check-changes:
   runs-on: ubuntu-latest
  #  outputs:
  #    client_changed: ${{ steps.client_changed.outputes.client}}
  #    server_changed: ${{ steps.server_changed.outputes.server}}
   steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check for chenges in client
      id:   client_changed
      uses: dorny/paths-filter@v3
      with:
       filters: |
         frontend:
           - 'frontend/**'
       

    - name: Check for chenges in server
      id:   server_changed
      uses: dorny/paths-filter@v3
      with:
       filters: |
         backend2:
           - 'backend2/**'
       
  client:
    needs: check-changes
    runs-on: ubuntu-latest
    # if: needs.check-changes.outputes.client_changed =='true'
    steps:
      
     - name: Checkout code
       uses: actions/checkout@v4

     - name: login docker hub
       uses: docker/login-action@v3
       with: 
          username: faizansari2025
          password: Bandarfaiz
     - name: create a docker image
       run: |
        cd frontend
        docker build -t faizansari2025/blog-client . 
        
        docker push faizansari2025/blog-client

     -  name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

     -   name: Add Hostinger VPS to known hosts
         run: |
          mkdir -p ~/.ssh
          ssh-keyscan 147.93.104.143 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

     -   name: Deploy via SSH
         run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@147.93.104.143 "your-deployment-script.sh"
         env:
           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}           
    
         
                  


  server:
          needs: check-changes
          runs-on: ubuntu-latest
          # if: needs.check-changes.outputes.server_changed =='true'
          steps:
            
            - name: Checkout code
              uses: actions/checkout@v4
            - name: docker login
              uses: docker/login-action@v3
              with:
                 username: faizansari2025
                 password: Bandarfaiz

            - name: build docker image
              run: |
               cd backend2
               docker build -t faizansari2025/blog-server .

               
               docker push faizansari2025/blog-server
 
            