name: swiggy-workflow
on:
  push:
    branches:
    -  main

jobs:
  check-chnages:
    runs-on: ubuntu-latest
    outputs:
      client_changed: ${{stpes.client_changed.outputs.client_changed}}
      server_changed: ${{stpes. server_changed.outputs.server_changed}}
    steps:
      - name: checkout code 
        uses: actions/checkout@v4

      - name: check changes
        id:  client_changed
        uses: dorny/paths-filter@v3 
        with:
          filters: 'frontend/**'

      - name: check changes
        id:  server_changed
        uses: dorny/paths-filter@v3 
        with:
            filters: 'backend2/**'
          
  client:
    
    runs-on: ubuntu-latest
    if: needs.check-changes.outputs.client_changed=='true'
    steps:
        - name: nice work
          run : echo 'client has been changed'