name: swiggy-workflow
on:
  push:
    branches:
    -  main

jobs:
  check-chnages:
    runs-on: ubuntu-latest
    outputs:
      client_changed: ${{steps.client_changed.outputs.client_changed}}
      server_changed: ${{steps.server_changed.outputs.server_changed}}
    steps:
      - name: checkout code 
        uses: actions/checkout@v4

      - name: check changes
        id:  client_changed
        uses: dorny/paths-filter@v3 
        with:
          filters: |
            frontend:
              'frontend/**'

      - name: check changes
        id:  server_changed
        uses: dorny/paths-filter@v3 
        with:
            filters: |
            backend2:
              'backend2/**'
              
          
  client:
    
    runs-on: ubuntu-latest
    if: needs.check-changes.outputs.client_changed=='true'
    steps:
        - name: nice work
          run : echo 'client has been changed'

  server:
    
    runs-on: ubuntu-latest
    if: needs.check-changes.outputs.server_changed=='true'
    steps:
        - name: nice work
          run : echo 'client has been changed'