name : blog workfllow


on:
 push:
   branches:
    - main

jobs:
  check-changes:
   runs-on: ubuntu-latest
   outputs:
     client_changed: ${{ steps.client_changed.outputes.client}}
     server_changed: ${{ steps.server_changed.outputes.server}}
   steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check for chenges in client
      id:   client_changed
      uses: dorny/paths-filter@v3
      with:
       filters: |
         frontend:
           - 'frontend/**'
       

    - name: Check for chenges in server
      id:   server_changed
      uses: dorny/paths-filter@v3
      with:
       filters: |
         backend2:
           - 'backend2/**'
       
  client:
    needs: check-changes
    runs-on: ubuntu-latest
    if: needs.check-changes.outputes.client_changed =='true'
    steps:
      - name: Nice
        run: echo "client has chnaged"
  

  server:
          needs: check-changes
          runs-on: ubuntu-latest
          if: needs.check-changes.outputes.server_changed =='true'
          steps:
            - name: Nice
              run: echo "server has chnaged"